# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pitchslapp' do
    pod 'Firebase', '>= 2.5.1'
    pod 'SwiftForms'
end

target 'PitchslappTests' do

end

target 'PitchslappUITests' do

end

